## 1. Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr = np.arange(2,50,3)
arr

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

## 2. Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.¶

In [2]:
a = list(input("enter 5 elements").split())
b = list(input("enter 5 elements").split())
a=np.array(a)
b=np.array(b)
c=np.concatenate((a,b))
print(c)
a = np.sort(a)
a

enter 5 elements1 4 5 2 4
enter 5 elements1 5 2 4 5
['1' '4' '5' '2' '4' '1' '5' '2' '4' '5']


array(['1', '2', '4', '4', '5'], dtype='<U1')

## 3. Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]],[[2, 4, 5],[5, 6, 7]]])

print(b.ndim)
print(c.ndim)
print(d.ndim)
print(b.size)
print(c.size)
print(d.size)


1
2
3
5
6
12


## 4. How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [4]:
arr = np.array([1,2,4,5,6])
arr = np.expand_dims(arr,axis=(0,1))
arr

array([[[1, 2, 4, 5, 6]]])

## 5. Consider two square numpy arrays. Stack them vertically and horizontally.

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## 6.How to get unique items and counts of unique items?

In [6]:
x = np.array([1,1,1,2,2,2,5,2,1,1,3])
unique, counts = np.unique(x, return_counts=True)
print(np.asarray((unique, counts)).T)

[[1 5]
 [2 4]
 [3 1]
 [5 1]]
